name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies and PyInstaller
        run: pip install -r requirements.txt pyinstaller -U

      - name: Build Executables
        run: |
          # Build GUI
          pyinstaller -y -F -w -i "extra/DUCE-LOGO.ico" --clean --name "DUCE-GUI-windows" `
          --add-data "base.py;." `
          --add-data "default-duce-gui-settings.json;." `
          --add-data "README.md;." `
          --add-data "LICENSE;." `
          "gui.py"
          # Build CLI
          pyinstaller -y -F -c -i "extra/DUCE-LOGO.ico" --clean --name "DUCE-CLI-windows" `
          --add-data "base.py;." `
          --add-data "default-duce-cli-settings.json;." `
          --add-data "README.md;." `
          --add-data "LICENSE;." `
          "cli.py"

      - name: Upload Windows Package
        uses: actions/upload-artifact@v4
        with:
          name: DUCE-windows-package
          path: ./dist/
